### ISSUE TITLE
"index out of range" on macOS Ventura 13.1

### ISSUE THREAD

**Issue by fuzzes** [Sorrow446/Nugs-Downloader#22]
Hi! I built from source for `darwin`/`amd64` and I'm running into the following error:

```
$ GOOS=darwin GOARCH=amd64 go build
$ ./main https://www.nugs.net/on/demandware.store/Sites-NugsNet-Site/default/Stash-QueueVideo?skuID=[redacted]&showID=[redacted]&perfDate=[redacted]&artistName=[redacted]&location=[redacted]&format=liveHdStream
[1] 45424
[2] 45425
[3] 45426
[4] 45427
[5] 45428
[2]   Done                    showID=[redacted]
[3]   Done                    perfDate=[redacted]
[4]-  Done                    artistName=[redacted]
[5]+  Done                    location=[redacted]
$
 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
	  |___|

Signed in successfully - no active subscription

Item 1 of 1:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.paidLstream({0x2058bc9b4, 0xc}, {0xc000222160, 0x20}, 0xc000277f50?, 0x2?)
	/Users/[redacted]/git/Nugs-Downloader/main.go:1516 +0x18f
main.main()
	/Users/[redacted]/git/Nugs-Downloader/main.go:1603 +0x4cb
```

I'm not sure if this is a fatal issue: the script hasn't terminated, but I'm not seeing anything in my output directory. Any suggestions for troubleshooting/fixing would be greatly appreciated!

**Comment by Sorrow446** [comment]
It is a fatal error. Could you message me on Discord (same username)?

**Comment by fuzzes** [comment]
I can no longer reproduce the issue, so I'll close it. I suspect this was due to the widespread issues with Nugs on July 16.
